import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer'

const styles = StyleSheet.create({
  page: { padding: 30, fontFamily: 'Helvetica' },
  header: { fontSize: 20, marginBottom: 20, fontWeight: 'bold' },
  subHeader: { fontSize: 14, marginBottom: 10, color: '#555' },
  section: { marginBottom: 15 },
  label: { fontSize: 10, color: '#777', marginBottom: 2 },
  value: { fontSize: 12, marginBottom: 5 },
  row: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 5 },
  item: { fontSize: 11, marginBottom: 3 },
  docLink: { fontSize: 10, color: '#2563eb', marginBottom: 2 }
})

export const ApplicationPDF = ({ application, property, items, documents }: any) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <Text style={styles.header}>Rental Application Report</Text>
      <Text style={styles.subHeader}>{property?.address}{property?.unit ? `, ${property.unit}` : ''}</Text>
      {property?.rent && <Text style={styles.value}>Monthly Rent: ${property.rent}</Text>}

      <View style={styles.section}>
        <Text style={styles.label}>Applicant Name</Text>
        <Text style={styles.value}>{application.name || 'N/A'}</Text>
        <Text style={styles.label}>Email</Text>
        <Text style={styles.value}>{application.email || 'N/A'}</Text>
        <Text style={styles.label}>Phone</Text>
        <Text style={styles.value}>{application.phone || 'N/A'}</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.header}>Checklist Items</Text>
        {items.map((item: any) => (
          <View key={item.id} style={styles.row}>
            <Text style={styles.item}>{item.category}: {item.item_text}</Text>
            <Text style={styles.item}>{item.condition || '—'}</Text>
          </View>
        ))}
      </View>

      <View style={styles.section}>
        <Text style={styles.header}>Uploaded Documents</Text>
        {documents.map((doc: any) => (
          <Text key={doc.id} style={styles.docLink}>{doc.type}: {doc.url}</Text>
        ))}
        {documents.length === 0 && <Text style={styles.value}>No documents uploaded.</Text>}
      </View>

      <Text style={{ fontSize: 9, marginTop: 30, color: '#aaa' }}>Generated by TenantKit</Text>
    </Page>
  </Document>
)